### ISSUE TITLE
add Neon servers

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/status#640]
Coqui - [https://coqui.neonaibeta.com](https://coqui.neonaibeta.com/status)
Coqui 2 - [https://coqui.neonaialpha.com](https://coqui.neonaialpha.com/status)
Coqui 3 - [https://coqui.neonaiservices.com](https://coqui.neonaiservices.com/status)

Nemo - [https://nemo.neonaialpha.com](https://nemo.neonaialpha.com/status)

**Comment by goldyfruit** [comment]
Done https://github.com/OpenVoiceOS/status/commit/320e04a6e133d9138c1896b5d749da1fd54272aa
